### ISSUE TITLE
gnark should be able to export a Solidity verifier

### ISSUE THREAD

**Issue by gbotrel** [ConsenSys/gnark#12]
All needed informations should be in the `VerifyingKey` data structure. 

The export / convert function takes as input the `VerifyingKey` and a `io.Writer` . Writes on the `io.Writer` a solidity smart contract that takes as input a proof and a set of public inputs (as defined in the `VerifyingKey`). 

Low priority task.

**Comment by weijiekoh** [comment]
I'd suggest using the verifier code here as is has been audited: https://github.com/appliedzkp/semaphore/blob/master/contracts/sol/verifier.sol

Audit report: https://github.com/appliedzkp/semaphore/blob/master/audit/Audit%20Report%20Summary%20for%20Semaphore%20and%20MicroMix.pdf
