### ISSUE TITLE
bug: Deserialization fails for large circuits

### ISSUE THREAD

**Issue by liyue201** [Consensys/gnark#1208]
Deserialization fails when the circuit reaches around 100 million constraints

```
panic: cbor: exceeded max number of elements 2147483647 for CBOR array
```

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* gnark v0.9.1

**Comment by readygo67** [comment]
could you provide more infos about this issue? for example 
1. how many constraints of your circuit?
2. how to reproduce this problem?

**Comment by ivokub** [comment]
Interesting, the bound is 2^31, which is somewhat limited by the internal representation we use, and it is interesting to see that you hit the limit with smaller circuits. Are you sure the circuit has approximately 100M constraints? Imo we have tried using PLONK circuits of size approximately 2^27 and it serializes well.

What proof system (Groth16, PLONK) are you using and what is the exact constraint count?

**Comment by liyue201** [comment]
This place is over the limit

https://github.com/Consensys/gnark/blob/3421eaa7d544286abf3de8c46282b8d4da6d5da0/constraint/bn254/system.go#L159

I see that the latest code has been optimized and this problem should no longer exist.
