### ISSUE TITLE
Help!!! please help me solve a simple question

### ISSUE THREAD

**Issue by George551556** [Consensys/gnark#1210]
if api.Cmp(hidden1, circuit.CZero) == 1 {
		api.Println("xxx")
		hidden1 = api.Sub(hidden1, hidden1)
	} else {
		api.Println("yyy")
	}
1. what is the return-type of api.Cmp( ) ?
2. I know there notes in the api.go, but the code above always ouput "yyy"
3. Please tell me how to use the func correctly Thanks!!!

**Comment by George551556** [comment]
I can pay $$$ for your great help!

**Comment by ivokub** [comment]
Sorry, we do not offer paid support. We try to respond to the issues in timely manner, but don't promise any response time.

`api.Cmp` returns a `frontend.Variable` which is not a fixed value. It is initialized during proving time. So it is incorrect to use if-else clause for deciding the proceeding computation.

Instead, you should use the returned value to compute the next variable a la
```go
cmpRes := api.Cmp(hidden1, circuit.CZero)
cmpIsOne := api.IsZero(api.Sub(cmpRes, 1))
hidden1 := api.Select(cmpIsOne, X, 0)
```

**Comment by George551556** [comment]
It is indeed useful thank you



---Original---
From: "Ivo ***@***.***&gt;
Date: Wed, Jul 24, 2024 16:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Consensys/gnark] Help!!! please help me solve a simple question(Issue #1210)




 
Sorry, we do not offer paid support. We try to respond to the issues in timely manner, but don't promise any response time.
 
api.Cmp returns a frontend.Variable which is not a fixed value. It is initialized during proving time. So it is incorrect to use if-else clause for deciding the proceeding computation.
 
Instead, you should use the returned value to compute the next variable a la
 cmpRes := api.Cmp(hidden1, circuit.CZero) cmpIsOne := api.IsZero(api.Sub(cmpRes, 1)) hidden1 := api.Select(cmpIsOne, X, 0)
