### ISSUE TITLE
bug: malicious hint in BN254 final exp check

### ISSUE THREAD

**Issue by yelhousni** [Consensys/gnark#1213]
## Description
reported in https://github.com/Consensys/gnark/pull/1143#pullrequestreview-2150219385 by [feltroidprime](https://github.com/feltroidprime).
TL;DR: we check in-circuit that `f * w  == c^λ` where `c` and `lambda` come from a hint. A malicious prover can provide the incorrect hints `w = c^λ/f` and `c` and the check will pass. The original [paper](https://eprint.iacr.org/2024/640.pdf) suggests in 7.1 to check in circuit that `(1-w)(f-w)(f^2-w) == 0` where `f^i` is the non-trivial 3rd root of unity. The paper then proves that `w` can only be in Fp3 and suggest to constraint it so. 

## Possible Fix

Since `w = w0+w1*u` is in Fp3, then `w^(p^3) = w` and `w^(p^6) = w`. On the other hand `w^(p^6) = conj(w) = w0 - w1*u` and thus `w = w0` in Fp6. We can force in-circuit `w1` to be 0 and retrieve `w0` from the hint:
```go
cubicNonResiduePower := E12{
    C0: E6{
                B0: E2{A0: *res[12], A1: *res[13]},
                B1: E2{A0: *res[14], A1: *res[15]},
                B2: E2{A0: *res[16], A1: *res[17]},

    },
    C1: (*pr.Ext6.Zero()),
}
```

**Comment by ivokub** [comment]
Would it make sense to also amend the non-malicious default hint such that when the provided previous pairing value is 0, then we wouldn't get into the infinite loop [here](https://github.com/Consensys/gnark/blob/master/std/algebra/emulated/sw_bn254/hints.go#L112-L116)?
