### ISSUE TITLE
How to assign a bigint value？

### ISSUE THREAD

**Issue by doubiliu** [Consensys/gnark#1232]
I'm writing some elliptic curve related operations and an error occurs when assigning a big.int variable to the input.
For example:
`	assignment := &ECDSAEncryptionCircuit[emulated.Secp256k1Fp, emulated.Secp256k1Fr]{
		r: emulated.ValueOf[emulated.Secp256k1Fr](XXX),
	}`

report
`=== RUN   TestEcdsaEncryptionCircuit
19:11:11 INF compiling circuit
ignoring uninitialized slice: r_Limbs []frontend.Variable
19:11:11 INF parsed circuit inputs nbPublic=32 nbSecret=0
ignoring uninitialized slice: r_Limbs []frontend.Variable
ignoring uninitialized slice: r_Limbs []frontend.Variable
19:11:11 ERR recomposing constant error="zero length slice input"
19:11:11 ERR recomposing constant error="zero length slice input"
19:11:11 ERR recomposing constant error="zero length slice input"
19:11:11 ERR recomposing constant error="zero length slice input"
19:11:11 ERR recomposing constant error="zero length slice input"
19:11:11 ERR recomposing constant error="zero length slice input"
19:11:11 ERR recomposing constant error="zero length slice input"
19:11:11 ERR recomposing constant error="zero length slice input"
19:11:12 INF building constraint builder nbConstraints=199696
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method`

**Comment by ivokub** [comment]
Can you make the field `r` public by uppercasing it and then re-run the test? In Go variables which are lowercase are not exported, preventing initializing variables.
