### ISSUE TITLE
cs: (experimental) add support for IF and FOR 

### ISSUE THREAD

**Issue by gbotrel** [ConsenSys/gnark#14]
Idea: 
```go
// signature
func (cs *CS) IF(condition *Constraint, ifBlock func(), elseBlock ...func())
```
```go 
	// example: 
	circuit.IF(condition, func() {
		circuit.IF(circuit.NOT(condition2), func() {
			// if block
			circuit.MUL(...)
		}, func() {
			// optional else block
			circuit.DIV(...)
		})		
	})
```
```go
        const maxLoops = 100
	for i := 0; i < maxLoops; i++ {
		circuit.IF(circuit.IS_SMALLER(myContraint, i), func() {
		})
                myConstraint = circuit.ADD(myConstraint, 1)
	}
```

Work in progress. Likely needs better syntax, may need new type of constraints /  "boolean predicates".

**Comment by ThomasPiellard** [comment]
In the example that you gave: the IS_SMALLER(..) that would return a bool is actually difficult to write as a r1c (I didn't find how to do it at the time I was writing the cs.go file).

I suggest to keep things simple  at first step and write an 
`IF(c, func(..) []*constraints, func(..) []constraints) []*constraints`
where c is a variable that has been boolean constrained. Writing the IF like this would be syntaxic sugar to avoid writing by hand the two paths and then the SELECT at the end.
