### ISSUE TITLE
architecture: move ecc/ package into its own repository

### ISSUE THREAD

**Issue by gbotrel** [ConsenSys/gnark#16]
Once #15 and #13 are done would be a good time to move `ecc` into its own repository.

`gnark` would only contain Constraint Systems and Proving protocols. The crypto primitives they rely on would be reference in go.mod . 

Current `cs` pacakge needs refactoring (move out subpackages, etc).

**Comment by ThomasPiellard** [comment]
Do you mean just the code for the arithmetic in the elliptic curve or the pairing as well? For the pairing it's still possible but different path has to be taken according to the curve (for instance the BN12 family has some extra operations after the Miller loop to compensate the loop shortening).

**Comment by gbotrel** [comment]
@ThomasPiellard the whole ecc/ package, should be a different github repo once it's stable. 
A project like `goff`, but to generate `ecc` tower + pairing. It will have a `generated` subfolder that other projects like `gnark` can reference through go modules. Question is should it be `ecc` only or should it be more general to support other crypto primitives `gnark` may need in the future?
