### ISSUE TITLE
Solver hints with multiple outputs

### ISSUE THREAD

**Issue by gbotrel** [ConsenSys/gnark#175]
Solve hints currently forces the signature to return only one output.

However, if multiple variables are linked (bit decomposition, external-proof verification, ...) then it is wasteful (somethings prohibitively so) to compute the same hint n-times for each bit. 

Two ideas; 
1. from @AlexandreBelling  Make "stateful hints" solving order deterministic 
2. modify or add a new API `[N]Variable <- cs.NewHint(N, ..)`

**Comment by ivokub** [comment]
Have you started working on it? If not, then I would have a look.

**Comment by gbotrel** [comment]
All yours :) 
Ideally I'ld like to keep only 1 API for hints, no strong ideas on this topic 👍

**Comment by ivokub** [comment]
For the second option - we can not return a variable-length array, but only slice. In that case, the arguments to NewHint wouldn't change, but the method would just return a slice of variables. So, the signature would be:
```
API.NewHint(f hint.Function, inputs... frontend.Variable) []frontend.Variable
```

We would also need to change the signature of `hint.Function` to:
```
type Function func(curveID ecc.ID, inputs []*big.Int, result []*big.Int) error
```

For me it seemed initially, that this wouldn't be a good approach, as then the user would need to know which elements in the returned `frontend.Variable` slice are which, but this can be documented with the hint function. I'll implement it and see how it looks.

**Comment by gbotrel** [comment]
> Edit: Oh, I see - the variables are allocated before the function is evaluated and we do not know the number of resulting variables ahead of time.

Yes, that would force the user to pass `api.NewHint(n, ...)` , n being the size of the expected output. Or have hints functions be a struct implementing an interface rather than a function. Don't know.
