### ISSUE TITLE
use GLV scalar multiplication for std/bandersnatch

### ISSUE THREAD

**Issue by yelhousni** [Consensys/gnark#196]
scalar multiplication on bandersnatch in [gnark-crypto](https://github.com/ConsenSys/gnark-crypto/blob/87e7abd83ece7467bb5ec85615421ba3491f0ef8/ecc/bls12-381/twistededwards/bandersnatch/point.go#L430) uses endomorphism-based acceleration. gnark/std should do the same with hints for scalar decomposition.

**Comment by yelhousni** [comment]
#263

**Comment by gbotrel** [comment]
Related to #268

**Comment by yelhousni** [comment]
done
