### ISSUE TITLE
How to use pointer and slice in the circuit struct?  

### ISSUE THREAD

**Issue by bluarry** [ConsenSys/gnark#201]
Hi everyone ,i want to use zkp in my work, 
how can i use pointer or Slice in Circuit struct Defination?

When i use Pointer my definations are as follow:
```go
type Node struct {
	data frontend.Variable
	next *Node
}
type List struct {
	size uint64
	head *Node
	tail *Node
}
type listCircuit struct {
	datas *List
	Y frontend.Variable `gnark:",public"`
}
func (circuit *listCircuit) Define(curveID ecc.ID, api frontend.API) error {
	l:=circuit.datas.Getdatas()  //l is a slice

	ans:=api.Constant(0)
	for _,x:=range l{
		ans=api.Add(ans,x)
	}
	api.AssertIsEqual(circuit.Y,ans)
	return nil
}
```
In the case, it will Prove failed,even i use the right test case.

When i use slice it will also compile error
My Defination are as followed :
```go
type listCircuit struct {
	lt [] frontend.Variable
	Y frontend.Variable `gnark:",public"`
}
func (circuit *listCircuit) Define(curveID ecc.ID, api frontend.API) error {
	ans:=api.Constant(0)
	for _,x:=range circuit .lt{
		ans=api.Add(ans,x)
	}
	api.AssertIsEqual(circuit.Y,ans)
	return nil
}
```
this case will alse Prove error.

So how can i solve this problem??

**Comment by gbotrel** [comment]
Pointers & slices are legal, but need to be allocated by the developer before calling `frontend.Compile`. 

`frontend.Compile` "walks through" the circuit structure to detect (and allocate internally) the witness. If slices are not allocated or pointers are nil, they can't be part of the witness .
