### ISSUE TITLE
[std] Implement Poseidon hash

### ISSUE THREAD

**Issue by gbotrel** [Consensys/gnark#207]

**Comment by stefan2904** [comment]
For the record, there are implementations by others:

- https://github.com/bnb-chain/gnark/tree/zkbnb-dev/std/hash/poseidon
- https://github.com/philsippl/gnark-playground/blob/poseidon/examples/poseidon/poseidon.go

**Comment by yelhousni** [comment]
@ThomasPiellard implemented Poseidon2 https://github.com/Consensys/gnark/pull/1300
