### ISSUE TITLE
Support non-native field arithmetic

### ISSUE THREAD

**Issue by gbotrel** [ConsenSys/gnark#211]
* Necessary step for PCD (proof carrying data schemes)
* See xjsnark

Related issues for tracking:
- [x] #302 
- [x] #315 
- [x] #314 
- [x] implement *easy*- and *hard*-mode for users. In easy mode, the package reduces values immediately after operations, but in hard mode the user is responsible to reduce the values in time. The library should panic if the inputs are incompatible, though.

**Comment by JameWade** [comment]
so,will i get a mod function?

**Comment by ivokub** [comment]
#302 completes initial task. See also #314 for fake-API implementation.

**Comment by ivokub** [comment]
> so,will i get a mod function?

@JameWade -- sorry for the late reply. We have implemented modular arithmetic for any modulus in #302. Could you have a look if the gadget would work for you?
