### ISSUE TITLE
std/sw: implement GLV (GLS) scalar multiplication in G2

### ISSUE THREAD

**Issue by ivokub** [ConsenSys/gnark#223]
From #222:

> this GLV improvement works also for G2. So the same code should be used in g2.go (as in gnark-crypto). That is said, we can have a 4-dimensional GLV (GLS) in sw_bls12377/g2 and 8-dimensional in in sw_bls24315/g2 (instead of 2-dimensional in g1). This is low priority as it is not used in groth16 verifier gadget and it's not implemented in gnark-crypto yet. But it might be worth it once we implement PlonK verifier gadget (or just KZG verifier) as it involves a single scalar mul in G2.

**Comment by yelhousni** [comment]
#305 closes this.
