### ISSUE TITLE
Multidimensional arrays support problem

### ISSUE THREAD

**Issue by SherLzp** [Consensys/gnark#236]
Are multidimensional arrays not supported? I remember it was supported in older versions.

come up with this error for Merkle Proofs:

`when parsing variable MerkleProofsAccountBefore_0_0: can't set fr.Element from type []frontend.Variable`

MerkleProofsAccountBefore is this:

`MerkleProofsAccountBefore       [NbAccountsPerTx][AccountMerkleLevels]Variable`

@gbotrel

**Comment by gbotrel** [comment]
Hi -- which version are you using ? Can you describe the issue with a reproductible code snippet? 

On v0.6.0 seems to work fine, on develop too. Some commits in between may not be stable on that front.

**Comment by gbotrel** [comment]
@SherLzp can I close this issue ?

**Comment by SherLzp** [comment]
Hi, I find the problem but I'm not sure if it is a problem.

The problem comes from here:

```golang
type Proof struct {
....
MerkleProofs [FixedCount][FixedCount]Variable
}

// when we have a function to get something like []Variable
func ConstructFixedProof() [FixedCount]Variable {.....}

// then if we set it into the merkle proofs, for example
Proof.MerkleProofs[index] =  ConstructFixedProof()

// then it will occur errors we mentioned

```
@gbotrel

**Comment by gbotrel** [comment]
@SherLzp when do this happens:
```
// then if we set it into the merkle proofs, for example
Proof.MerkleProofs[index] =  ConstructFixedProof()
``` 
Inside the Define() ? Witness creation? Please submit enough code to reproduce the issue 👍  

What gnark version do you use?

**Comment by SherLzp** [comment]
@gbotrel 
gnark version is 0.6.0

The function `ConstructFixedProof()` is out of Define(), just used for set witness.

**Comment by drakstik** [comment]
@gbotrel @SherLzp did this ever get solved? Couldn't find any references to multi dimensional arrays. If you know of any of those would appreciated.

**Comment by drakstik** [comment]
HI guys, @gbotrel  @SherLzp is this issue still open? I am trying to work with 2D arrays as well, but I get this issue:

`
// An N by N Matrix. Let N = 3 for this example.
type Matrix struct {
	X [N][N]frontend.Variable `gnark:"X"`
	Y frontend.Variable       `gnark:",public"`
}

func (circuit *Matrix) Define(api frontend.API) error {
	add_X:= api.Add(circuit.X[0][0], circuit.X[1][1], circuit.X[2][2])
	api.AssertIsEqual(circuit.Y, add_X)
	return nil
}

func main() {
        var circuit Matrix
	ccs, _ := frontend.Compile(ecc.BN254.ScalarField(), r1cs.NewBuilder, &circuit)

	// groth16 zkSNARK: Setup
	pk, vk, _ := groth16.Setup(ccs)

	// witness definition
	row:= [3]frontend.Variable{1, 2, 3}
	row2 := [3]frontend.Variable{1, 2, 3}
	row3 := [3]frontend.Variable{1, 2, 3}

	matrix := [3][3]frontend.Variable{row, row2, row3}

	assignment := Matrix{X: matrix, Y: 6} // X is secret, Y is public.
	witness, _ := frontend.NewWitness(&assignment, ecc.BN254.ScalarField())
	publicWitness, _ := witness.Public()

	// groth16: Prove & Verify
	proof, _ := groth16.Prove(ccs, pk, witness) // This proof can be sent alongside verification and public witness Y (i.e. the output).
	groth16.Verify(proof, vk, publicWitness)
}
`

When I run it I get:
`
22:15:01 INF compiling circuit
22:15:01 INF parsed circuit inputs nbPublic=1 nbSecret=9
22:15:01 INF building constraint builder nbConstraints=1
22:15:01 WRN circuit has unconstrained inputs
panic: unrecognized R1CS curve type

goroutine 1 [running]:
github.com/consensys/gnark/backend/groth16.Setup({0x0?, 0x0?})
        /home/draxtik/go/pkg/mod/github.com/consensys/gnark@v0.8.0/backend/groth16/groth16.go:286 +0x4a5
main.main()
        /home/draxtik/PhotoProof/src/main.go:$$$ +0x7c
exit status 2
`

Please help!
