### ISSUE TITLE
style: remove backend identifier from frontend.Compile signature

### ISSUE THREAD

**Issue by ivokub** [ConsenSys/gnark#245]
The long-term goal is to decouple completely the front end (arithmetic circuit to constraint system) and back end (from constraint system to proof and verification). Right now there are a lot of share types and variables which prevent doing that cleanly and requires quite a lot of refactoring.

However, as a first step, we should at least remove the reference to the backend in `frontend.Compile(curveID ecc.ID, zkpID backend.ID, circuit Circuit, opts ...CompileOption)` as there is a bit more to it. Right now, we support compiling to R1CS and SparseR1CS, and they are correspondingly used as inputs to the Groth16 and PLONK proving systems. However, there are other possible backends which could take the corresponding constraint systems as inputs (which we may implement in the future).

Another aspect to consider is that we currently support setting a custom builder as `Compile` option. However, this shouldn't be the default way to set the output constraint system as this requires setting a compile option (which is in contradiction with the term "option").

So, before we start changing anything, I would ask opinions on how the interface should look:
1. create a new package `github.com/consensys/gnark/constraintsystem` (simplify?) and for now define only the IDs of different constraints systems there: `type ID uint8`, `const (UNKNOWN ID = iota; R1CS; SparseR1CS)`. Then define `Compile` as `frontend.Compile(curveID ecc.ID, csID constraintsystem.ID, circuit Circuit, opts ...CompileOption)`. When doing this, I wouldn't yet move anything else related to CS to the new package as it would be quite large refactoring.
2. Use generics - create a new package as previously, but also define constraint `CSBuilder` and then define `Compile` as `Compile[CS CSBuilder](curveID ecc.ID, circuit Circuit, opts ...CompileOption)`. At first step I wouldn't change the output signature, but at some point we could also make the returned CS to be parametrized by `CSBuilder` constraint. This allows to have a type-safe way to call the particular backends.
3. Remove the backend identifier from the arguments and require that the builder is set as a compile option: `frontend.Compile(curveID ecc.ID, circuit Circuit, opts ...CompileOption)`
4. Remove the `WithBuilder` compile option and make it mandatory: `frontend.Compile(curveID ecc.ID, builder NewBuilder, circuit Circuit, opts ...CompileOption)`
5. something else?

I think it may be just to early for 1 and 2. For 1 it makes sense to do with the rest of decoupling, for 2 we need to wait until the generics really mature (and after that we need to do a massive refactoring).

Third one is also ugly, as compilation should be possible without setting any options.

I think the fourth option makes sense, but it puts a pressure on the developer who needs to know what back end takes which type of constraint system as input. To simplify the user experience a bit, we should have a `DefaultBuilder()` method in the back end packages which return something. But this still keeps some kind of coupling.

**Comment by ivokub** [comment]
A link to Go generics playground how the future version with generics could look like: https://gotipplay.golang.org/p/x4z-T8p1gx8

**Comment by ThomasPiellard** [comment]
I prefer option 4: it allows maximum flexibility, for instance it covers the case where one type of constraint system is implemented in 2 different ways (for instance one might imagine having a plonk compiler fast but not optimised, and one optimised but costly).

**Comment by gbotrel** [comment]
5. (maybe) what about removing frontend.Compile. And having a "Compiler" interface{}. Then, developer calls `r1cs.Compile(circuit, cuveID, options...) --> R1CS` Then groth16 takes as input a typed R1CS, instead of an interface frontend.CompiledConstraintSystem. 
But we still have R1CS that implements frontend.CompiledConstraintSystem and expose only what's needed ?
