### ISSUE TITLE
perf: R1CS solver should schedule its constraint resolution in parallel

### ISSUE THREAD

**Issue by gbotrel** [ConsenSys/gnark#251]
Currently, the solver is single-threaded. Its execution time is negligible compared to the proof creation, in usual scenarios. 

However, when running the Solver for very large circuits (50M+constraints) on many-cores machines, the single-threaded part hurts, and solving (that is finding the solution vector used to create the proof) is more time consuming than the zkSNARK creation itself.

**Comment by ChuWenFeng** [comment]
I noticed this problem last year and implemented it earlier. 
when I notice this issues, I reimplemented it in master.
[https://github.com/ChuWenFeng/gnark/blob/CWF/internal/backend/bn254/cs/r1cs.go](parallel R1CS solver)
Just on the bn254 curve.
There are 1000 unrelated signatures in our project. solver time Reduced from 18 seconds to 3 seconds
