### ISSUE TITLE
hints in gadgets are not registered when packages are not imported

### ISSUE THREAD

**Issue by ivokub** [ConsenSys/gnark#264]
The problem appears when both the constraint system and witness are obtained by deserializing data.

Maybe add a new package which imports all hints in gadgets (`backend/hint/all` etc.) which has only a single side-effect of importing all hints from gadgets and registering. This package should then be imported by the compiler and provers.

**Comment by gbotrel** [comment]
not a big fan of the registry pattern here (well the one for the #245  too :) ). 

I think the R1CS / SparseR1CS when it calls solve, should be able to check which hint it was "compiled" with (at least a string name with package) and output an error message to say that said hint is not injected. But I'ld rather have the user do "r1cs.Solve(witness, mygadget.MyHint...)" than to import a package for its sideeffect.

Let's sit on that one a bit, it seems there are couple of refactoring change on the horizon that needs careful thinking 👍
