### ISSUE TITLE
implement in-circuit `ToTernary` 

### ISSUE THREAD

**Issue by yelhousni** [ConsenSys/gnark#269]
Currently we have in-circuit binary decomposition `api.ToBinary` implemented with hints. It would be useful to have also a base-3 decomposition (or base-5 too).

**Comment by yelhousni** [comment]
Also `To2NAF` might be interesting to try few things.

**Comment by gbotrel** [comment]
Need some preliminary work ( #270  ) . 
Maybe also a good occasion to move some `bits` operations in a `std/bits` or `std/math/bits` package to avoid surcharging the base API 👍
