### ISSUE TITLE
Importing circuits from bellman

### ISSUE THREAD

**Issue by whyrusleeping** [ConsenSys/gnark#29]
Hello from the Filecoin team!

We would like to be able to use this library to ship a pure go version of filecoin that does not need to depend on bellman. We have existing circuits defined in bellman, but i'm not sure what the best way to go about using gnark to verify their outputs is.

**Comment by gbotrel** [comment]
Hello 👋 

Probably need a bit more context on that one; if you switch to `gnark` do you intend to use `bellman` in the network, in another implementation? If not (ie you don’t need full interopability), then the short answer is likely to rewrite the circuits in `gnark`, we have a new release coming soon which should make that straightforward unless you need very fancy crypto primitives in your circuits. That would also offer the advantage to have the circuit code in pure Go, which we aim to be compatible with other proof systems than Groth16.

Now for the longer answer, the flow for both library is similar: 
1. frontend (circuit code)  -> R1CS 
2. setup (R1CS)  -> proving key, verifying key
3. prove (R1CS, proving key, witness)  -> proof
4. verify (verifying key, proof, public part of the witness) -> ok / nok. 

The hard part of the interopability is the R1CS. There is no guarantees that `gnark` and `bellman` will express the circuit code into the same set of rank 1 constraints. Most importantly, solving this rank 1 constraint system (which happens during proof generation, to generate “circuit wire values” from the witness), is done in a very different way, that’s library-specific. 
Verifying bellman-generated proof with `gnark` should be possible without too much trouble, as it does not depend on the R1CS (but is not currently implemented)

**Comment by whyrusleeping** [comment]
Yeah, the idea is that (at least at first) we would keep using bellman on the proving side (in the miner software) and verify proofs on the 'full node' side of things. So, verifying a proof made in bellman with gnark.

Beyond that, given your increased proving perf over bellman, I would eventually like to be able to generate the proofs in go, but thats going to be a lot more work because all the surrounding calling code is also in rust.

**Comment by gbotrel** [comment]
Noted, created #30 , likely not going to be implemented in the coming weeks but will ping you when we do :-) .

**Comment by whyrusleeping** [comment]
Much appreciated! Thanks!
