### ISSUE TITLE
how can i print the proof into number?

### ISSUE THREAD

**Issue by chrisyang2003** [ConsenSys/gnark#303]
proof, err := groth16.Prove(r1cs, pk, witness)
fmt.Println(reflect.TypeOf(proof).String())

**Comment by chrisyang2003** [comment]
> 
send the proof to remote server to verfiy

**Comment by gbotrel** [comment]
hello -- please refer to this section in the docs; https://docs.gnark.consensys.net/en/latest/HowTo/serialize/#compression
