### ISSUE TITLE
Is the rollup example complete?

### ISSUE THREAD

**Issue by zhiqiangxu** [ConsenSys/gnark#308]
It seems there's no verification of the relationship of `RootHashesAfter` and `RootHashesBefore`, each is only verified independently, is there something I'm missing ?

**Comment by ThomasPiellard** [comment]
Hi @zhiqiangxu , on develop and master the rollup circuit is in fact not complete, some inputs are unconstrained for example. It will be fixed ( it is fixed on the branch feat/fri_verifier_circuit, also on this branch the snark circuit for verifying a Merkle proof is simplified).
