### ISSUE TITLE
Docs: 64bits: amd64 or arm64 ?

### ISSUE THREAD

**Issue by Jorropo** [ConsenSys/gnark#31]
While reading the readme, I've sawn the 64bits optimised mention. (https://github.com/ConsenSys/gnark/blob/master/README.md#prerequisites)
Does this include arm64 or is it only amd64 ? This might be nice to precise in the README 😄

**Comment by gbotrel** [comment]
Indeed, field arithmetic in assembly is `amd64` only for now in [goff](https://github.com/consensys/goff)  (but still compiles on `arm64`) . 
a new `gnark` release is coming soon with a lot of documentation clean up, will add this precision, thanks for raising 👍

**Comment by Jorropo** [comment]
thx for this clarification
