### ISSUE TITLE
refactoring: `frontend` APIs should take a field as input, not a curve

### ISSUE THREAD

**Issue by gbotrel** [ConsenSys/gnark#312]
* PlonK + FRI --> not curve dependent, but field dependent.
* Fuzz testing solvers against big int test engine --> not curve dependent, but field dependent.

It seems that the frontend APIs should not take a ecc.ID (ie a curveID) as parameter, but a “field id”. That would mean changing frontend.Compile api, but also the API interface (which has a CurveID() method) and the hint signature.

**Comment by ivokub** [comment]
How will the actual curve be decided? Will there be any default mapping?

This proposal would actually make sense with #314 if we allow to give any field as an argument. But then we would need to decide separately which curve to work on.
