### ISSUE TITLE
Issue with gnark installation on go1.14.5 darwin/amd64

### ISSUE THREAD

**Issue by gokulsan** [ConsenSys/gnark#32]
I am getting the following errors while trying to get the gnark library using go get -u

# github.com/consensys/gnark/backend/bn256
src/github.com/consensys/gnark/backend/bn256/fft.go:139:28: cannot use expo (type uint64) as type *big.Int in argument to subGroup.GeneratorSqRt.Exp
# github.com/consensys/gnark/backend/bls377
src/github.com/consensys/gnark/backend/bls377/fft.go:139:28: cannot use expo (type uint64) as type *big.Int in argument to subGroup.GeneratorSqRt.Exp
# github.com/consensys/gnark/backend/bls381
src/github.com/consensys/gnark/backend/bls381/fft.go:139:28: cannot use expo (type uint64) as type *big.Int in argument to subGroup.GeneratorSqRt.Exp

**Comment by gbotrel** [comment]
Thanks for raising -- should be fixed on v.0.3.X (now merged into `master`)
