### ISSUE TITLE
unable to install on Ubuntu 18 with go version go1.10.4 linux/amd64

### ISSUE THREAD

**Issue by themighty1** [ConsenSys/gnark#34]
Running go get github.com/consensys/gnark
results in an error log:

# github.com/consensys/gnark/backend/r1cs/r1c
../../../../go/src/github.com/consensys/gnark/backend/r1cs/r1c/term.go:27:31: syntax error: unexpected b000, expecting semicolon or newline or )
../../../../go/src/github.com/consensys/gnark/backend/r1cs/r1c/term.go:35:31: syntax error: unexpected b00, expecting semicolon or newline or )
# github.com/consensys/gurvy/bn256/fr
../../../../go/src/github.com/consensys/gurvy/bn256/fr/arith.go:30:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bn256/fr/arith.go:31:13: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bn256/fr/arith.go:32:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bn256/fr/arith.go:39:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bn256/fr/arith.go:40:14: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bn256/fr/arith.go:41:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bn256/fr/arith.go:48:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bn256/fr/arith.go:49:13: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bn256/fr/arith.go:50:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bn256/fr/arith.go:51:14: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bn256/fr/arith.go:51:14: too many errors
# github.com/consensys/gurvy/bls377/fr
../../../../go/src/github.com/consensys/gurvy/bls377/fr/arith.go:30:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bls377/fr/arith.go:31:13: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls377/fr/arith.go:32:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls377/fr/arith.go:39:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bls377/fr/arith.go:40:14: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls377/fr/arith.go:41:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls377/fr/arith.go:48:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bls377/fr/arith.go:49:13: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls377/fr/arith.go:50:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls377/fr/arith.go:51:14: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls377/fr/arith.go:51:14: too many errors
# github.com/consensys/gurvy/bls381/fr
../../../../go/src/github.com/consensys/gurvy/bls381/fr/arith.go:30:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bls381/fr/arith.go:31:13: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls381/fr/arith.go:32:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls381/fr/arith.go:39:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bls381/fr/arith.go:40:14: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls381/fr/arith.go:41:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls381/fr/arith.go:48:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bls381/fr/arith.go:49:13: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls381/fr/arith.go:50:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls381/fr/arith.go:51:14: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls381/fr/arith.go:51:14: too many errors
# github.com/consensys/gurvy/bw761/fr
../../../../go/src/github.com/consensys/gurvy/bw761/fr/arith.go:30:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bw761/fr/arith.go:31:13: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bw761/fr/arith.go:32:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bw761/fr/arith.go:39:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bw761/fr/arith.go:40:14: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bw761/fr/arith.go:41:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bw761/fr/arith.go:48:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bw761/fr/arith.go:49:13: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bw761/fr/arith.go:50:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bw761/fr/arith.go:51:14: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bw761/fr/arith.go:51:14: too many errors
# github.com/consensys/gurvy/bls377/fp
../../../../go/src/github.com/consensys/gurvy/bls377/fp/arith.go:30:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bls377/fp/arith.go:31:13: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls377/fp/arith.go:32:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls377/fp/arith.go:39:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bls377/fp/arith.go:40:14: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls377/fp/arith.go:41:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls377/fp/arith.go:48:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bls377/fp/arith.go:49:13: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls377/fp/arith.go:50:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls377/fp/arith.go:51:14: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls377/fp/arith.go:51:14: too many errors
# github.com/consensys/gurvy/bls381/fp
../../../../go/src/github.com/consensys/gurvy/bls381/fp/arith.go:30:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bls381/fp/arith.go:31:13: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls381/fp/arith.go:32:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls381/fp/arith.go:39:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bls381/fp/arith.go:40:14: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls381/fp/arith.go:41:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls381/fp/arith.go:48:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bls381/fp/arith.go:49:13: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls381/fp/arith.go:50:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls381/fp/arith.go:51:14: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bls381/fp/arith.go:51:14: too many errors
# github.com/consensys/gurvy/bn256/fp
../../../../go/src/github.com/consensys/gurvy/bn256/fp/arith.go:30:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bn256/fp/arith.go:31:13: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bn256/fp/arith.go:32:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bn256/fp/arith.go:39:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bn256/fp/arith.go:40:14: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bn256/fp/arith.go:41:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bn256/fp/arith.go:48:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bn256/fp/arith.go:49:13: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bn256/fp/arith.go:50:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bn256/fp/arith.go:51:14: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bn256/fp/arith.go:51:14: too many errors
# github.com/fxamacker/cbor
../../../../go/src/github.com/fxamacker/cbor/encode.go:867:11: v.MapRange undefined (type reflect.Value has no field or method MapRange)
../../../../go/src/github.com/fxamacker/cbor/encode.go:948:11: v.MapRange undefined (type reflect.Value has no field or method MapRange)
# github.com/consensys/gurvy/bw761/fp
../../../../go/src/github.com/consensys/gurvy/bw761/fp/arith.go:30:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bw761/fp/arith.go:31:13: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bw761/fp/arith.go:32:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bw761/fp/arith.go:39:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bw761/fp/arith.go:40:14: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bw761/fp/arith.go:41:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bw761/fp/arith.go:48:11: undefined: bits.Mul64
../../../../go/src/github.com/consensys/gurvy/bw761/fp/arith.go:49:13: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bw761/fp/arith.go:50:10: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bw761/fp/arith.go:51:14: undefined: bits.Add64
../../../../go/src/github.com/consensys/gurvy/bw761/fp/arith.go:51:14: too many errors
# github.com/stretchr/testify/assert
../../../../go/src/github.com/stretchr/testify/assert/assertions.go:1703:5: undefined: errors.Is
../../../../go/src/github.com/stretchr/testify/assert/assertions.go:1726:6: undefined: errors.Is
../../../../go/src/github.com/stretchr/testify/assert/assertions.go:1749:5: undefined: errors.As
../../../../go/src/github.com/stretchr/testify/assert/assertions.go:1766:7: undefined: errors.Unwrap
../../../../go/src/github.com/stretchr/testify/assert/assertions.go:1770:7: undefined: errors.Unwrap

**Comment by gbotrel** [comment]
Thanks for raising. You'll need to install a more recent version of Go (some standard apis were introduced in Go >= 1.12). Will amend the readme to make the Go version requirement explicit
