### ISSUE TITLE
ToBinary constraint sometimes fails to verify

### ISSUE THREAD

**Issue by Nik-U** [ConsenSys/gnark#35]
I've been having problems with valid proofs about scalar multiplications on Twisted Edwards curves occasionally failing to verify. While trying to locate precisely what constraints are causing it to fail, I've encountered similar behavior with the `ToBinary` constraint, which happens to be the first step of scalar multiplication. The following is the minimum working example:

```
package main

import (
	"fmt"

	"github.com/consensys/gnark/backend/groth16"
	"github.com/consensys/gnark/frontend"
	"github.com/consensys/gurvy"
)

type simpleCircuit struct {
	X frontend.Variable
}

func (circuit *simpleCircuit) Define(_ gurvy.ID, cs *frontend.ConstraintSystem) error {
	cs.ToBinary(circuit.X, 64)
	return nil
}

func main() {
	var circuit simpleCircuit
	r1cs, err := frontend.Compile(gurvy.BN256, &circuit)
	if err != nil {
		fmt.Printf("Failed to compile circuit: %v\n", err)
		return
	}
	provingKey, verifyingKey := groth16.Setup(r1cs)

	for {
		var proverAssignment simpleCircuit
		proverAssignment.X.Assign(uint64(1234))
		proof, err := groth16.Prove(r1cs, provingKey, &proverAssignment)
		if err != nil {
			fmt.Printf("Failed to prove statement: %v\n", err)
			return
		}

		var verifierAssignment simpleCircuit
		verifierAssignment.X.Assign(0)
		if err := groth16.Verify(proof, verifyingKey, &verifierAssignment); err != nil {
			fmt.Printf("Proof failed to verify: %v\n", err)
			return
		}
	}
}
```

This proof doesn't actually show anything useful, as the variables created by `ToBinary` are simply ignored. Nonetheless, `groth16.Verify` returns a `pairing doesn't match` error after being run for long enough. On my machine, a proof will fail to verify typically within a few minutes, after thousands have been successfully verified. I would expect this proof to always verify.

Proofs still fail in the same way if I change `gurvy.BN256` to `BLS377`, `BLS381`, or `BW761`. They also fail if the circuit generation and setup is moved inside the loop (but of course that makes each iteration run slower). There seems to be some setups that don't fail even after a while—when encountering those I restart the experiment. This either suggests that this problem only affects certain setups, or I simply did not let it run long enough in those cases.

Running a similar experiment with the "cubic" example does not seem to show this non-deterministic failure, suggesting that it's something to do with the more complex constraints involved in `ToBinary`.

Interestingly, I've never seen this code reproduce the problem when being run through the Delve debugger. It only happens when running a compiled binary normally. Perhaps this suggests that there might be some sort of memory corruption going on and this circuit is more susceptible to it than the "cubic" example.

Tested with Gnark 0.3.3 and Go 1.15.2 on linux/amd64.

**Comment by ThomasPiellard** [comment]
Hi @Nik-U , thanks for raising the issue, I have been doing some tests on my side, can you run your example using GOMAXPROCS=1?
`GOMAXPROCS=1 go run main.go`
With GOMAXPROCS=1 I don't have the issue anymore, I just want to be sure it's not only on my machine. Otherwise indeed it fails around 3~5k trials in average.

**Comment by Nik-U** [comment]
After running it for a few hours with `GOMAXPROCS=1`, the error did not appear. It's also true that if a given proof ever fails to verify, then it will continue to fail to verify with repeated `groth16.Verify` calls. So it indeed seems to be something wrong in the prover that is triggered by parallelism.

**Comment by gbotrel** [comment]
Found the data race (in `gurvy`, the optional parameter to the multiExp was mishandled), fixed and merged in `master`.
