### ISSUE TITLE
groth16: deserialization from io.Reader

### ISSUE THREAD

**Issue by Nik-U** [ConsenSys/gnark#36]
Currently, it does not seem to be possible for users to restore `ProvingKey`, `VerifyingKey`, or `Proof` structures that have been saved to anything other than a file. This makes it difficult to store proving/verifying keys in app resources or transmit proofs over a network, among many other potential uses. Ideally, it should be possible to deserialize these structures from an arbitrary `io.Reader`.

Currently, the `groth16` package provides `ReadProvingKey`, `ReadVerifyingKey`, and `ReadProof`, but these functions only work for reading from files. A simple way to resolve this issue is to modify these functions to take an `io.Reader` instead of a `path string`, and then use Gnark's `gnark/io.Read` instead of `gnark/io.ReadFile` internally. Alternatively, a second set of functions could be added with the generalized behavior.

It is not possible for users to call `gnark/io.Read` manually, because the decoder requires the target to be a pointer to a concrete struct, and these are all defined in `internal` packages. For example, there appears to be no way for a user to create a struct of type `internal/backend/bls381/groth16.Proof` without either performing a new proof, or using `groth16.ReadProof` to read one from a file. Passing in an interface (the usual type exposed to users) as the target also does not work, because it will be `nil` and `Read` calls `GetCurveID` on the target before attempting to decode it.

**Comment by gbotrel** [comment]
Some work on those lines is in our backlog; we have various user requirements on the serialization topic and will do our best to allow "standard" io.Reader / io.Writer, better manage curve type encoding, have gnark objects implement standard interfaces like `BinaryMarshaler` etc.  
As you noted, we want to simplify API surface and forbid user to instantiate curve specific objects, which is a bit annoying for deserialization.

**Comment by mdj33** [comment]
very agree Nik-U,  it is currently difficult to transmit proofs over a network, like to encode proof to string and decode it in app and restore the original struct value by hex.EncodeToString. p
revious version it is gob. now it is cbor.NewDecoder(reader), it seems hard to encode bytes to string.

**Comment by gbotrel** [comment]
@mdj33 we're on it :) . `gob` is not suitable for large data. We're currently implementing point serialization in `gurvy` matching standard if available or other binary protocol used by other ecc/pairing libraries. 

The encoding won't change the fact that `gnark` will offer APIs w/ `io.Reader` / `io.Writer` , library user can then chose what to do with the stream of bytes.

**Comment by robert-zaremba** [comment]
Re serialization: why not using Protocol Buffers? This is what we are using now in Cosmos-SDK, and there was lot of research and experimentation before that move. 
Protocol Buffers are very efficient, and became a market standard for cross-languages binary serialization.

**Comment by gbotrel** [comment]
So, it's not a `cbor` vs `protobuf` question; thing is in `gnark`, the main objects that needs to be serialized are the circuit (i.e the `R1CS`), the `ProvingKey`, the `VerifyingKey` and the `Proof` . 

`ProvingKey`, `VerifyingKey` and  `Proof` contains field elements and ecc points, and having a straightforward encoding makes sense as for example, you may need to decode them "on chain" (in Ethereum in solidity). 

For these objects, the encoding won't be `protobuf` or `cbor`, but [will follow this](https://github.com/zcash/librustzcash/blob/6e0364cd42a2b3d2b958a54771ef51a8db79dd29/pairing/src/bls12_381/README.md#serialization) and adapt to any upcoming IETF standardization. 
Might have a "`gnark` metadata header".  

There are some efforts for `R1CS` standardization, but we're not on that train yet, and would like to keep doors open to represent circuits in a `gnark` friendly way, for other prover systems too. 

However, we feel it's less important, as the `R1CS` is unlikely to transit on the network in a typical workflow (unless we try to be interoperable with other libraries). 

Choice for the `R1CS` went to `cbor` vs `protobuf` as performance without code generation and schemalessness makes this more flexible while we are under a v0.X.X release cycle.
