### ISSUE TITLE
readWitness seems not include secret input discard function as previous version

### ISSUE THREAD

**Issue by mdj33** [ConsenSys/gnark#37]
io.ReadWitness(fInputPath, r1csInput)

previous:
func (assignments Assignments) DiscardSecrets() Assignments {
	toReturn := NewAssignment()
	for k, v := range assignments {
		if v.IsPublic {
			toReturn[k] = v
		}
	}
	return toReturn
}

**Comment by gbotrel** [comment]
Thanks for reporting, indeed the issue was when trying to assign public values only to a witness, fixed in #38
