### ISSUE TITLE
Need an example/documentation of large variable support and  integer overflow verification 

### ISSUE THREAD

**Issue by maoudia-via** [ConsenSys/gnark#373]
Hello,

I am trying to define a circuit which can deal with large variables and might need to split the terms used in the constraint definition into smaller terms modulo q where q<p.
I have a number of questions which might be better solved by a working example. I can also help build the example with some guidance. My questions are:
- When checking for overflow, can I use the comparison operator defined with the compiler ? 
`Cmp(i1, i2 [Variable](https://pkg.go.dev/github.com/consensys/gnark/frontend#Variable)) [Variable](https://pkg.go.dev/github.com/consensys/gnark/frontend#Variable)`
- Same question for splitting the terms: Can that be done using the operations defined here : https://pkg.go.dev/github.com/consensys/gnark@v0.7.0/frontend
- Does this (splitting + checking overflow) need to be done after each new constraint added to the circuit ? 
Any guidance will be appreciated !

Thanks !

**Comment by ivokub** [comment]
Hi, @maoudia-via. Actually, we have just landed a very preliminary version of non-native arithmetic gadget in gnark for exactly the use-case you have. It is still not in the master branch, but will be included in the next release. Until that, you can have access to it on the develop branch. Please note that we are still actively working on it to make it perform better and to add more features.

The gadget is in `std/math/emulated` package. The gadget should be sufficiently documented and there are tests which describe the gadget usage. The general idea is that in circuit struct you use `emulated.Element` for witness variables and in circuit definition you wrap the "native" API using `emulated.New[T]` (where T is a type parameter indicating which field you want to emulate) and then use the wrapped API as is. All the splitting, width restrictions, reductions etc. are done by the API wrapper.

If this gadget is sufficient, but you have additional questions on how to use it, then for questions about using the gadget it is better to use the [discussions](https://github.com/ConsenSys/gnark/discussions) feature of Github and keep issues for tracking bugs/features.

**Comment by maoudia-via** [comment]
Thank you @ivokub for your response. From your description, this seems to address the use case I described perfectly. I will give it a try and come back to you  on the discussions channel for any questions. 
Do you have a target date for when this would make it to master ?

**Comment by ivokub** [comment]
Hmm. I'll try to figure out when we will have a feature freeze and create a new release. I will ask from the team and get back to you this week.

**Comment by ivokub** [comment]
@maoudia-via -- I believe the release should come this month. It is mostly behind refining the non-native field emulation. We currently only have `frontend.API` wrapper to perform computations over non-native field, but when implementing other gadgets we have understood that it still makes sense to have some explicit methods (modular reduction, mostly, but in the future maybe also modular exponentiation) in field emulation.
