### ISSUE TITLE
 w.CurveID.Info undefined (type ecc.ID has no field or method Info)

### ISSUE THREAD

**Issue by zilin-zhou** [ConsenSys/gnark#379]
This problem occurs when you go build. The first time it didn't appear, now it's been this problem, I downloaded the package again, or reported the same error! If you know, please help me down! Thank you!

![image](https://user-images.githubusercontent.com/95197986/194706282-4f6a3949-7052-422d-a617-f566fd740132.png)

**Comment by ivokub** [comment]
Hi @zilin-zhou, have you updated the dependencies? More specifically, when using gnark v0.7.0, then you should be using gnark-crypto v0.7.0 as a dependency. Can you show the lines in `go.mod` for gnark-crypto?

**Comment by zilin-zhou** [comment]
> 
I've solved the problem! Thank you
