### ISSUE TITLE
Option for disabling randomness

### ISSUE THREAD

**Issue by Tabaie** [ConsenSys/gnark#404]
For debugging implementations of protocols, it is often useful to be able to turn off randomization, ensuring that different runs of the same test are identical. This makes tracking values and finding errors easier. Following are two possible solutions and their relative pros/cons:

1. A build tag like `disable_randomness`
2. Option to inject a custom random reader, defaulting to the way randomization is currently done.

**TODO: Example for using 1**

Example for using 2:
```go

type ListReader struct {
  values [][]byte
}

func (r *ListReader) Read(p []byte) (n int, err error) {
  if len(r.values) == 0 {
    err = fmt.Errorf("no more values to read")
  } else if len(r.values[0]) != len(p) {
    err = fmt.Errorf("unexpected length")
  } else {
    n = copy(p, r.values[0])
    r.values = r.values[1:]
  }
  return

}

func NewBn254ListReader(values ...{}interface) ListReader{
  reader := ListReader{ make([][]byte, len(values)) }
  for i, v := range values {
    var x fr.Element
    x.SetInterface(v)
    reader.values[i] = x.Bytes()
  }
  return reader
}

...

rand := NewListBn254ListReader(1, 2, 3, 4, 5)
pk, vk, err := groth16.Setup(_r1cs, groth16.WithRandReader(&rand))
```

* 2 introduces more code complexity than 1 and imposes some performance penalty (likely negligible)
* 2 is more flexible than 1. The appropriate kind of "fake randomization" may depend on the application and is best left to the user.
* 2 gives the user another chance to "mess things up". However, if the default setting is randomization as we currently use it, that would not be a problem.

**Comment by ivokub** [comment]
For me the two options seem quite similar. Even if we have `disable_randomness` tag, then we have to go through the whole codebase to plug the random sources. So, for both cases I guess we need some global interface/context which defines which random source to use. And implementation wise I guess it doesn't make a very big difference if it is controlled by a build tag or by defining in runtime. What I would avoid is to have some global contexts, because they may be mutable and lead to some weird bugs.

**Comment by Tabaie** [comment]
Totally agree on the trouble with global settings. I don't think 2 needs global settings though. Essentially what would happen is that any protocol instance hands down its randomization settings to its subprotocols. So the setting would not be "global" in the sense that other protocol instances running in parallel within the same app would not be affected.

@ThomasPiellard what do you think?

**Comment by gbotrel** [comment]
@Tabaie I like the `io.Reader` / `groth16.WithRandReader(&rand)` option, seems like a non-invasive / standard way of doing things 👍

**Comment by gbotrel** [comment]
(you may need to add it for the PlonK setup too though, for consistency in the lib APIs )

**Comment by gbotrel** [comment]
@Tabaie how important is this? it contaminates more than it look like, since using a `io.Reader` interface for randomness also forces the field element API to accept this as randomness source.

**Comment by Tabaie** [comment]
I wouldn't say it's super important. Whenever we're modifying something on the backend level, we could just point to a local copy of gnark-crypto and just modify `Element.SetRandom` there. @ThomasPiellard is a stakeholder here too though.
