### ISSUE TITLE
test engine error with hints

### ISSUE THREAD

**Issue by Tabaie** [ConsenSys/gnark#429]
```go
type testHintCircuit struct {
	X frontend.Variable
}

func (c *testHintCircuit) Define(api frontend.API) error {
	if zero, err := api.Compiler().NewHint(func(mod *big.Int, ins, outs []*big.Int) error {
		for _, out := range outs {
			out.SetInt64(0)
		}
		return nil
	}, 1); err == nil {
		api.AssertIsEqual(zero[0], c.X)
	} else {
		return err
	}
	return nil
}

func TestHint(t *testing.T) {
	assignment := testHintCircuit{X: 0}
	circuit := testHintCircuit{}
	test.NewAssert(t).SolvingSucceeded(&circuit, &assignment,
		test.WithBackends(backend.GROTH16), test.WithCurves(ecc.BN254))
}
```
fails with error message : `groth16(bn254): solver missing hint(s): [<<package_path>>.(*testHintCircuit).Define.func1]`

**Comment by gbotrel** [comment]
oh; you have to register the hint like so:

```go
var myHint hint.Function = func(mod *big.Int, ins, outs []*big.Int) error {
	for _, out := range outs {
		out.SetInt64(0)
	}
	return nil
}

func init() {
	hint.Register(myHint)
}

type testHintCircuit struct {
	X frontend.Variable
}

func (c *testHintCircuit) Define(api frontend.API) error {
	if zero, err := api.Compiler().NewHint(myHint, 1); err == nil {
		api.AssertIsEqual(zero[0], c.X)
	} else {
		return err
	}
	return nil
}

func TestHint(t *testing.T) {
	assignment := testHintCircuit{X: 0}
	circuit := testHintCircuit{}
	test.NewAssert(t).SolvingSucceeded(&circuit, &assignment,
		test.WithBackends(backend.GROTH16), test.WithCurves(ecc.BN254))
}

```

**Comment by Tabaie** [comment]
I think it's necessary to be able to have inline-defined hints that are not registered globally. For applications such as commitments, GKR solving and proving often dynamic (not known at compile time) information is necessary to determine how exactly the hint would work. As an example, the commitment computing hint will need information from the verifying key that is not only not known at program compile time, but is not even known at circuit compile time. The GKR solver needs to know about the structure of the GKR circuit being solved. Thus, being bound to using named functions registered globally will not work, especially if multiple gnark circuits are being worked on at the same time.

**Comment by gbotrel** [comment]
this translates into a much more complicated issue; the typical workflow is you write a circuit, **serialize** it, and use it later on. 

So the solver needs a mechanism to say "this wire is solved by this function". Doing a lambda, you could register it anonymously and derived some sort identifier at runtime, but if you go through serialization and use it in another process... unless we go a more cumbersome path (scripting language), I don't see a very obvious solution.
