### ISSUE TITLE
add `api.IsEqual -> (0, 1)` and `api.IsDifferent  -> (0, 1)`

### ISSUE THREAD

**Issue by gbotrel** [Consensys/gnark#432]
currently we have `AssertIsEqual` and `AssertIsDifferent`, which don't allow composability and use in conjunction with `api.Select` for example.

**Comment by ivokub** [comment]
But we have `api.IsZero` and can implement the methods as `api.IsEqual(a,b) = api.IsZero(api.Sub(a,b))` and `api.IsDifferent(a,b) = api.Sub(1, api.IsZero(a,b))`.

I'd rather have fewer than more methods in API to make implementing it (GKR, field emulation, turboPLONK etc.) easier.

**Comment by gbotrel** [comment]
fair point, for my immediate use case that's probably enough...  that being said, for the examples you cite (field emulation, turboPLONK) there may be more efficient way to encode the statement, and, for field emulation in particular, I wanted something independent of other APIs, but that's probably too niche.
