### ISSUE TITLE
WebAssembly binary can be built and loaded successfully but it makes "panic: runtime error: integer divide by zero" error"

### ISSUE THREAD

**Issue by crazybae** [ConsenSys/gnark#44]
I understand gnark does not support wasm env officially yet.
Nevertheless, I guess it can do by updating small portion of codes.
A sample code (mimc prove and verify) can be built as an wasm binary and loaded by a javascript (i.e., WebAssembly.instantiateStreaming) successfully due to the absence of cgo usages.
But on executing the wasm binary, the following errors occur immediately:

panic: runtime error: integer divide by zero
github.com/consensys/gnark/internal/backend/bn256/fft.precomputeExpTable(0x9a42b93a4388ee4f, 0x16c835b156abb91e, 0x5fcd5d77a3b49b70, 0x1d24a254e5e81852, 0x904000, 0x200, 0x200)
github.com/consensys/gnark/internal/backend/bn256/fft/domain.go:156 +0x16
github.com/consensys/gnark/internal/backend/bn256/fft.(*Domain).preComputeTwiddles.func2(0x9a42b93a4388ee4f, 0x16c835b156abb91e, 0x5fcd5d77a3b49b70, 0x1d24a254e5e81852, 0x904000, 0x200, 0x200)

I guess the errors would be removed with some new zero value handling logics in your new version.
I hope I can use your excellent gnark in my WebAssembly projects soon.

Thanks.

**Comment by gbotrel** [comment]
Hi,

We had a look at that few months back, here is [a gist](https://gist.github.com/gbotrel/b5d42259e5026c430a6c8da6fee0ce3d) (not compatible with current API signatures) for the verify op.

I think the best path while we don't support WASM officially is to duplicate the `groth16.Verify` code and build that as an independent project, without dependencies. 

The `groth16.Prove` will be extremely inefficient in WASM, are you looking at that part too? 

The issue you mentioned on the `backend/.../fft` packages is likely to appear on few other part of the code. 
Some components in `std` also indirectly depends on external go packages and most of them (last we checked) were difficult to run in WASM.
