### ISSUE TITLE
implement `api.MulAcc` in plonk frontend

### ISSUE THREAD

**Issue by gbotrel** [ConsenSys/gnark#447]
in 1 constraint instead of 2.

**Comment by ivokub** [comment]
I had a quick look at it when trying to optimise field emulation. I'm not sure but I feel that without custom gates cannot do. We would have to do `o <- a + b*c`, but we only have three wires.

However, if we could do in two wires, then it could help a lot :)

**Comment by gbotrel** [comment]
heh, it seems current version already does 1 constraint when c is a constant, so ... I can close this issue, nothing to do at the moment.
