### ISSUE TITLE
bug: fuzzer failures with non-native arithmetic

### ISSUE THREAD

**Issue by ivokub** [ConsenSys/gnark#484]
Fuzzer occasionally finds inputs to the field emulation gadget where the test engine succeeds but the prover fails. I have reduced the problem to the way we enforce width constraints for the witness elements. In automatic width enforcement we have:
```go
if !frontend.IsCanonical(a.Limbs[i]) {
	// this is not a variable. This may happen when some limbs are
	// constant and some variables. A strange case but lets try to cover
	// it anyway.
	continue
}
```
But `frontend.IsCanonical` only checks if the variable is `cs.Term` or `cs.LinearExpression` (or old PLONK versions of them). In test engine variables are `*big.Int` and we pass the automatic width enforcement.

So, what happens is that fuzzer creates some input which is not valid for field emulation (more than 64 bits) but the test engine doesn't fail. Then this invalid input is provided to the prover which fails and we get a fuzzing error.

Imo the options are:
* in test engine, wrap `*big.Int` into some struct with some additional metadata. Then we can also start differentiating between variables and constants (for now we have the test option to set all variables as consts or non-consts, which is far from good). Then add the new struct into the check in `frontend.IsCanonical` function.
* Make `IsCanonical` part of Compiler interface. Right now all places we use it has access to api, so it would technically work. But there may be cases where we want to check without API?

**Comment by ivokub** [comment]
@gbotrel, do you have any ideas for this one? Imo it annoys that we have random CI failure. It may hide some actual regressions.

**Comment by gbotrel** [comment]
I think option 2 would make sense; that `api.Compiler()` has an API that tells you if this is a known variable. But... it still is annoying for the test engine; 

To not add too much complexity; I check this function is used in 3 places. The one that could be problematic, that you linked;
```go
if !frontend.IsCanonical(a.Limbs[i]) {
			// this is not a variable. This may happen when some limbs are
			// constant and some variables. A strange case but lets try to cover
			// it anyway.
			continue
		}
```
Why don't we just add a `else` clause here, and if the limb is a big int, and larger than the width, well.. we panic? that would make sense both in circuit for constants & for the test engine, would it not?

**Comment by ivokub** [comment]
> Why don't we just add a `else` clause here, and if the limb is a big int, and larger than the width, well.. we panic? that would make sense both in circuit for constants & for the test engine, would it not?

Hmm, seems plausible. I'll have a think and try it out.
