### ISSUE TITLE
are there some constraints to judge the value bigger than zero?

### ISSUE THREAD

**Issue by mdj33** [ConsenSys/gnark#49]
as some scenario,  it is quit needed to constraint the value to bigger than zero.  like the MUSTBE_LESS_OR_EQ,  MUSTBE_MORE_OR_EQ is also expected.

**Comment by gbotrel** [comment]
Hello,

Would elements from this PR (#48) help reach your goal ?

"bigger than zero" is always true for field elements, except for Zero, so using "IsZero()" + "Select" statement may get you where you need.
