### ISSUE TITLE
Hint Generalization

### ISSUE THREAD

**Issue by Tabaie** [ConsenSys/gnark#499]
We need a generalization of hints so we can avoid the kind of hack-work currently existing in the BSB22 commitment codebase (there are some hint hacks in GKR-API as well but they're not so bad.)

This generalization (hintoids? injected variables?) has the following properties:
1. Like a hint, it produces a value depending on some public, private and internal variables and upon which other variables can depend.
2. Unlike a hint, it's not user-facing, but for internal use. (debatable)
3. Highly curve-dependent implementation: no unified big.Int based user-provided implementation. Values are passed as fr.Elements. Implementations are provided to/inside the backend.
4. Customized verification: a hint produces an internal value on which in-SNARK verification can be run. With injected variables, the verifier would be able to provide the value itself (for commitments, this is a commitment hashed onto fr)

**Comment by ivokub** [comment]
If we would have this, how would the field-specific hints be defined? Do we need to provide an implementation for every field using code generation or can we generalize a bit, assuming scalars to be up to `[6]uint64` (but usually 4) and then in runtime casting?

I don't understand point 4. - verifier usually doesn't run hints? Can you expand on this? Does it essentially mean that we can directly inject value as an hint output without going through hoops to modify existing hint functions? It would be useful.

**Comment by Tabaie** [comment]
The functions are just defined in each backend module on `fr.Element` in/out.

Point 4 is useful for BSB22 commitments. Since the verifier is given the commitment as a G1 point, amenable to proof-of-knowledge verification, but the commitment value in the circuit is an fr element, the verifier will need to do the hash-to-fr herself. I don't fully understand your other question but I think the answer may be yes 😁

Currently the whole thing is very tailor-made for BSB22 commitments and to be totally honest I'm not sure if it will be useful for much else. My main motivation is cleaning up the commitment codebase a bit. But once BSB22-for-Plonk is done I might come back and generalize it in a way that would be useful for GKR-API as well (also involving hint hacks but not quite in the same way.)

**Comment by gbotrel** [comment]
@Tabaie should we close that?

**Comment by Tabaie** [comment]
Yes I think so, until we come across another potential use case.
