### ISSUE TITLE
Support PLONK

### ISSUE THREAD

**Issue by SherLzp** [ConsenSys/gnark#52]
[PLONK](https://eprint.iacr.org/2019/953) is a new zk-snarks algorithm, which is based on Sonic. It can realize SRS (no longer need to generate CRS for each circuit separately), and it is very practical compared to Sonic. Can we modify gnark to support PLONK? I want to make some contributions to the project, so I have the following issues:
- PLONK's circuit construction method is not based on R1CS. Will we make a big modification on the existing code ?
- If the modifications are not significant, how will they be modified? Which parts of the code should be modified? Now gnark uses `ConstraintSystem` to define the Groth16 circuit, whether it is necessary to construct a new class or based on the existing `ConstraintSystem`.

**Comment by gbotrel** [comment]
Hello,

@ThomasPiellard is currently working on making the `frontend` compatible with both Groth16 and PLONK arithmetizations. 

Once that is done (PR likely coming in 2-3 weeks), we will see how to proceed for next steps, happy to ping you here if you want to participate.

**Comment by gbotrel** [comment]
@SherLzp if you are interested to contribute to PLONK in particular, one thing you could implement independently of the `frontend/` is the Kate commitments part. 
We have that on our backlog in about a month from now, but if you're willing to contribute a first version to the repo that could help `gnark` support PLONK sooner.

**Comment by SherLzp** [comment]
@gbotrel  Thanks for reply! I will try my best.

**Comment by gbotrel** [comment]
@SherLzp hi :) did you have time to work on that the past weeks?

**Comment by SherLzp** [comment]
@gbotrel  Sorry for that,  I'm recently working on a paper. I expected it to start in early March.
