### ISSUE TITLE
Test fails for a trivial circuit

### ISSUE THREAD

**Issue by aybehrouz** [ConsenSys/gnark#527]
Tests fail for the following simple circuit:
```go

type testCircuit struct {
	N frontend.Variable `gnark:",public"`
}

func (c *testCircuit) Define(api frontend.API) error {
	bits.ToBinary(api, c.N, bits.WithNbDigits(3))
	return nil
}

func TestTest(t *testing.T) {
	assert := test.NewAssert(t)

	assert.ProverSucceeded(&testCircuit{}, &testCircuit{N: 3})
}
```
```
=== RUN   TestTest/fuzz/bn254/groth16
    assert.go:80: errVars [assertIsEqual] 4 == 14914344159867638993849239390888276500196600227666715437247040087537991462988
        bits.toBinary
        	conversion_binary.go:93
        bits.ToBase
        	conversion.go:25
        bits.ToBinary
        	conversion_binary.go:18
        bits_test.(*testCircuit).Define
        	compare_test.go:15
        
    assert.go:80: errConsts <nil>
```

**Comment by gbotrel** [comment]
looks like it's a feature, rather than a bug; 
also the comment in the PR #522 doesn't capture the whole picture ; 
```go
decomposition and WithUnconstrainedOutputs option is not used,
 // then a proof can not be generated. If WithNbDigits
```

Technically, a proof **can** be generated, if the variable is in the correct range. So say if you have inputs to your circuit that you know are `uint8` (ie smaller than 256); then `bits.WithNbDigits(8)` makes sense. 

If the goal is to get "parts" of the bits, the circuit developer is better off getting the full bit decomposition and re-slicing the result (to ensure the bit decomposition matches the variable), maybe doc should mention that.. 

What use case are you interested in with `NbDigits` options exactly?

**Comment by aybehrouz** [comment]
> looks like it's a feature, rather than a bug;

This happens just because I'm not using the result of the function. For example, this does **NOT** fail:
```go

type testCircuit struct {
	N frontend.Variable `gnark:",public"`
}

func (c *testCircuit) Define(api frontend.API) error {
	out := bits.ToBinary(api, c.N, bits.WithNbDigits(3))
	api.AssertIsEqual(api.Add(out[0], out[1], out[2]), 2)
	return nil
}

func TestTest(t *testing.T) {
	assert := test.NewAssert(t)

	assert.ProverSucceeded(&testCircuit{}, &testCircuit{N: 3})
}
```

**Comment by aybehrouz** [comment]
> Technically, a proof **can** be generated, if the variable is in the correct range. So say if you have inputs to your circuit that you know are `uint8` (ie smaller than 256); then `bits.WithNbDigits(8)` makes sense.

You are correct. You are actually saying what I'm trying to say. The old comment was this:

>  If nbDigits is lower than the length of full decomposition, then nbDigits least significant digits are returned.

In the PR I've changed it to this:

> If nbDigits is lower than the length of full decomposition and WithUnconstrainedOutputs option is not used, then a proof can not be generated.

The first comment is not correct cause it won't give you least significant digits when for example you set nbDigits to 3 for a number which is 5 bits.

**Comment by aybehrouz** [comment]
Should we say it like this? 

> If nbDigits is lower than the length of the full decomposition and WithUnconstrainedOutputs option is not being used, then a proof can not be generated.

**Comment by gbotrel** [comment]
Visited this failing test; first I thought it was a fuzzing issue; but actually, the fuzzer pointed out a difference of behavior of the bit decomposition when we decompose a variable vs when we decompose a constant. 

When we decompose a variable, we do ensure by default that the decomposed bits match times the powers of 2 coeff match the input. We do not do that with constants, will fix.
