### ISSUE TITLE
feat: add ECMul precompile

### ISSUE THREAD

**Issue by gbotrel** [ConsenSys/gnark#571]
Before closing issue ensure we have a constraint count + a matching test with the exact interface.

**Comment by ivokub** [comment]
Costs:
Groth16 (with commit): 359895
PLONK (vanilla): 4431992
PLONK (with commit): 1239140
PLONK (with rangecheck): 464848, total rangechecks 30099 (ranges 48-63:2784; 64-79:27311; 80-75:4)

**Comment by ivokub** [comment]
Have test engine tests. Not integrated yet.
