### ISSUE TITLE
feat: add ECAdd precompile

### ISSUE THREAD

**Issue by gbotrel** [ConsenSys/gnark#572]
Before closing issue ensure we have a constraint count + a matching test with the exact interface.

**Comment by ivokub** [comment]
Costs:
Groth16 (with commit): 2279
PLONK (vanilla): 11712
PLONK (with commit): 6225
PLONK (with rangecheck): 876, total rangechecks 83 (ranges 48-63:11; 64-79:72)

Currently only test engine tests. Not integrated yet.
