### ISSUE TITLE
feat: add ECRecover precompile

### ISSUE THREAD

**Issue by gbotrel** [ConsenSys/gnark#574]
Before closing issue ensure we have a constraint count + a matching test with the exact interface.

**Comment by ivokub** [comment]
Costs:
Groth16 (with commit): 522773
PLONK (vanilla): 6492207
PLONK (with commit): 1764135
PLONK (with rangecheck): 686143, total rangechecks 43923 (ranges 64-79:43919; 80-75:4).

Only test engine tests. Not integrated yet.
