### ISSUE TITLE
Simple test gets stuck in an infinite loop 

### ISSUE THREAD

**Issue by aybehrouz** [ConsenSys/gnark#587]
It seems that this code somehow causes an infinite loop. I don't know if this is related to #585 or not.
```go
type cmpTest struct {
	A, B    frontend.Variable `gnark:",public"`
	WantCmp frontend.Variable
}

func (c *cmpTest) Define(api frontend.API) error {
	api.AssertIsEqual(c.WantCmp, api.Cmp(c.A, c.B))
	return nil
}

func TestCmp(t *testing.T) {
	assert := test.NewAssert(t)

	assert.ProverSucceeded(&cmpTest{}, &cmpTest{A: 2, B: 1, WantCmp: 1})
}
```

**Comment by gbotrel** [comment]
It is a bit slow but seems to run fine on `develop` (ie can't reproduce)
```
❯ go test -run=Cmp
PASS
ok      github.com/consensys/gnark/examples/cubic       13.937s
```

**Comment by aybehrouz** [comment]
You are right. I re-ran, and after 67 seconds it finished execution. Tests usually take less than 10 seconds on my laptop, so I guess I had not waited enough and after some while I had thought it wouldn't end.
