### ISSUE TITLE
feat: add default compress threshold for R1CS compile

### ISSUE THREAD

**Issue by ivokub** [ConsenSys/gnark#590]
References #583.

With the log-derivative variant of the range check gadget we get very large linear expressions which make compile times quite slow. We should set some reasonable default. I think a few hundred should suffice.

This makes estimating the constraint counts a bit difficult, but I think it is a necessary evil.

**Comment by ivokub** [comment]
Pinging @gbotrel, @ThomasPiellard -- do you have any suggestions for the default?

**Comment by gbotrel** [comment]
~200 to ~500?

**Comment by ivokub** [comment]
Ran small test with #583. There have 100k variables of 64bits:
```
Threshold | Time | NbConst
100 | 3.647273833 | 570238
200 | 4.050189500 | 567876
300 | 4.539864708 | 567093
400 | 5.025574792 | 566703
500 | 5.530525709 | 566469
```

But this is only for a single test and depends heavily on the circuit. I think there is no point going beyond 500. And because it is nice round number its easy to remember.

**Comment by gbotrel** [comment]
I mean, we could go for a default of 100, and ... when final version / we do release & care about the <~1% delta, we change manually depending on circuit.
