### ISSUE TITLE
Custom Modulus + External R1CS

### ISSUE THREAD

**Issue by furkan-ux** [ConsenSys/gnark#592]
Hello, firstly, thank you for this beautiful library!

I have two questions:

Firstly, I couldn't figure out how to use mod operation with gnark. In circom:

`Var xer = balance % r_prime;
`
What is the equivalent of this in the gnark circuit? 

Secondly, I have written and compiled my circuit in circom, now I have my r1cs and witness. Is it possible to use gnark only as a prover and also can I generate my witness from my r1cs (or sym etc.) of circom circuit, using gnark?

Thank you!!

**Comment by ivokub** [comment]
See discussion #595 .
