### ISSUE TITLE
Failed to generate code

### ISSUE THREAD

**Issue by alexeykiselev** [ConsenSys/gnark#6]
Hello, 
I've failed to re-generate generated code for the curves arithmetics.

**Steps to reproduce**

1. `goff` updated to current master and built with `make`.
1. `gnark` updated to current master.
1. In `gnark` folder `cd ecc/bls381`
1. and execute `go generate`
1. command fails with following output:

```
running goff version 0.1.0-alpha

generating fp/element.go
generating fp/arith.go
generating fp/element_test.go

running goff version 0.1.0-alpha

generating fr/element.go
generating fr/arith.go
generating fr/element_test.go
generating e2.go
generating e2_test.go
generating e6.go
generating e6_test.go
generating e12.go
error: template: :593:7: executing "" at <(eq .Fp6NonResidue "0,1") and (eq .Fp "258664426012969094010652733694893533536393512754914660539884262666720468348340822774968888139573360124440321458177")>: can't give argument to non-function eq .Fp6NonResidue "0,1"
exit status 255
bls381.go:14: running "go": exit status 1
```

**Comment by gbotrel** [comment]
Indeed, we noticed that with Go 1.14 update --> it was fixed in `develop` and now merged into `master`.

Note also that in this new merge, `goff` is used as a go.mod dependency, not a binary, to ensure proper versioning.
