### ISSUE TITLE
uniswap's liqudity is not working

### ISSUE THREAD

**Issue by Kumar5764** [ConsenSys/gnark#639]
hello sir. ll features are good , but uniswap's liqudity is not working andother is your ecosystem's ghost nft's nft is not claim in linea's network. so fix it. neither i realized all section are correct . 
thanks ..
0xf03C94C4A281719Ae0Eed57Cde1e4aEeE700dDd0

**Comment by gbotrel** [comment]
hello, issues regarding linea are unrelated to this repo (gnark), please visit https://discord.gg/consensys ! 👍
