### ISSUE TITLE
Default branch to `develop`

### ISSUE THREAD

**Issue by hussein-aitlahcen** [Consensys/gnark#766]
A lot of people think gnark is not maintained because of the default master branch having commits from february.
Maybe it would make more sense to have develop as default branch?

**Comment by ivokub** [comment]
Good point. We have a release planned but have been really busy with Linea zkEVM. I recon we will release by the end of the month of early August.

I'm not sure it would be safe to make develop the default branch as people are already using gnark for practical applications and we want to ensure the main branch is sound.
