### ISSUE TITLE
Division in GKR Circuits

### ISSUE THREAD

**Issue by Tabaie** [Consensys/gnark#800]
Necessary for emulated arithmetic etc. As with `frontend.API`, introduce a new input variable for the quotient and assert its product with the divisor equals the dividend.

**Comment by ivokub** [comment]
Not sure if necessary anymore. It may blowup GKR circuit size if we need to provide the inverses as witness. And for scalar multiplication can work with projective coordinates which are inversionless.

**Comment by Tabaie** [comment]
Yes that makes sense.
