### ISSUE TITLE
Importing issue for bls12377

### ISSUE THREAD

**Issue by 311923** [Consensys/gnark#822]
I am just getting started with go and gnark. I want to write a circuit that captures a ZK relation involving both hashes and BLS12-377 group elements. I have been able to run my code successfully in the gnark playground, but cannot independently run the code outside of the playground due to a package issue that I haven't been able to resolve. 

A simplified and easily reproducible version of my problem is as follows:

I start by directly taking the code from the readme of the Consensys/gnark repo:

```
package main

import (
	"github.com/consensys/gnark-crypto/ecc"
	"github.com/consensys/gnark/backend/groth16"
	"github.com/consensys/gnark/frontend"
	"github.com/consensys/gnark/frontend/cs/r1cs"
)

// CubicCircuit defines a simple circuit
// x**3 + x + 5 == y
type CubicCircuit struct {
	// struct tags on a variable is optional
	// default uses variable name and secret visibility.
	X frontend.Variable `gnark:"x"`
	Y frontend.Variable `gnark:",public"`
}

// Define declares the circuit constraints
// x**3 + x + 5 == y
func (circuit *CubicCircuit) Define(api frontend.API) error {
	x3 := api.Mul(circuit.X, circuit.X, circuit.X)
	api.AssertIsEqual(circuit.Y, api.Add(x3, circuit.X, 5))
	return nil
}

func main() {
	// compiles our circuit into a R1CS
	var circuit CubicCircuit
	ccs, _ := frontend.Compile(ecc.BN254.ScalarField(), r1cs.NewBuilder, &circuit)

	// groth16 zkSNARK: Setup
	pk, vk, _ := groth16.Setup(ccs)

	// witness definition
	assignment := CubicCircuit{X: 3, Y: 35}
	witness, _ := frontend.NewWitness(&assignment, ecc.BN254.ScalarField())
	publicWitness, _ := witness.Public()

	// groth16: Prove & Verify
	proof, _ := groth16.Prove(ccs, pk, witness)
	groth16.Verify(proof, vk, publicWitness)
}

```

I can then run `go run .` and the proof is generated without any problem. However, because I need to work with ZK relations about elliptic curve group elements, I need to import `"github.com/consensys/gnark/std/algebra/native/sw_bls12377"`.
However, if I then simply include that line as an import and run the program, I get the following error:

`no required module provides package github.com/consensys/gnark/std/algebra/native/sw_bls12377; to add it:
	go get github.com/consensys/gnark/std/algebra/native/sw_bls12377`.

If I then run the suggested `go get` command, I have the error:

`go: module github.com/consensys/gnark@upgrade found (v0.8.1), but does not contain package github.com/consensys/gnark/std/algebra/native/sw_bls12377`

I have googled around a bit and seen [various advice](https://stackoverflow.com/questions/62974985/go-module-latest-found-but-does-not-contain-package) about `go mod tidy` and `go clean -modcache`, but none of these have worked.

This must be a newbie issue. Can someone please help me out with this? Many thanks.

**Comment by gbotrel** [comment]
Hi, I think if you import gnark v0.9.0-alpha instead of v0.8.1 it should work

**Comment by 311923** [comment]
Thank you; this worked. For my own edification, how should I have found this version independently?

**Comment by ivokub** [comment]
Usually it is sufficient to do `go get github.com/consensys/gnark` and then `go mod tidy`. It uses the recursive dependencies from gnark to set the repository dependencies. gnark is still v0.XX and we do not enforce API stability strongly, so when upgrading transitive dependencies we may have conflicting versions between gnark and gnark-crypto.

Next time update only gnark dependency, then it should be good 👍
