### ISSUE TITLE
Getting BLS group generators

### ISSUE THREAD

**Issue by 311923** [Consensys/gnark#827]
What is the best way to get the generators from the groups associated with bls12-377?

I am looking at `gnark/std/algebra/native/sw_bls12377/g1.go` but do not see any way to get the generators. 

I had thought that something like the following would work, but it creates a nil pointer dereference:

```
import bls12377 "github.com/consensys/gnark/std/algebra/native/sw_bls12377"

var g bls12377.G1Affine
var a big.Int
a.SetString("1", 10)
g.ScalarMulBase(api, a)
```

**Comment by 311923** [comment]
I think that I have gotten things working as follows. Please advise on whether this is a sensible method. 

```
import(
bls12377 "github.com/consensys/gnark/std/algebra/native/sw_bls12377"
"github.com/consensys/gnark-crypto/ecc/bw6-761/fr"
)

var gen bls12377.G1Affine
	var genX big.Int
	genX.SetString("81937999373150964239938255573465948239988671502647976594219695644855304257327692006745978603320413799295628339695", 10)
	var genY big.Int
	genY.SetString("241266749859715473739788878240585681733927191168601896383759122102112907357779751001206799952863815012735208165030", 10)

	xCoord := new(fr.Element)
	xCoord.SetBigInt(&genX)

	yCoord := new(fr.Element)
	yCoord.SetBigInt(&genY)

	gen.X = *xCoord
	gen.Y = *yCoord
```

**Comment by ivokub** [comment]
This should work. There is a shorthand for assigning the values https://github.com/Consensys/gnark/blob/master/std/algebra/native/sw_bls12377/g1.go#L410.

You can also get dynamically the generator by calling https://github.com/Consensys/gnark-crypto/blob/master/ecc/bls12-377/bls12-377.go#L145. Then you won't have to hardcode the base point in the circuit.
