### ISSUE TITLE
bug: binary decomposition of a variable is not strictly asserted to be less than the modulus

### ISSUE THREAD

**Issue by lightning-li** [Consensys/gnark#852]
## Description

The bugfix for issue https://github.com/Consensys/gnark/issues/836 isn't complete. It seems the line https://github.com/Consensys/gnark/blob/master/std/math/bits/conversion_binary.go#L100C13-L100C13 used wrong parameters. It should be `cmper.MustBeLessOrEqCst(bits, bound, v)`

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* gnark version used (e.g. v0.8.1, `HEAD@develop`):
* gnark-crypto version used:
* go version (e.g. 1.20.6):
* Operating System and version:

**Comment by ivokub** [comment]
Hmm, looking at it I think it should actually be field modulus + 1. I will have a look at it and update your PR accordingly.

Thanks for letting know, somehow I missed that I was doing `LessEq` against constant not `Less`.
