### ISSUE TITLE
Question abount Plonk Roadmap

### ISSUE THREAD

**Issue by SteinsElite** [ConsenSys/gnark#87]
Hi there, i'm interested in L2, and i wonder it will take how much time to implennt the plonk system in your plan, and will you add a transform between the R1CS represention  and the plonk style

**Comment by gbotrel** [comment]
Hello --
`frontend.Compile` already (on the `develop` branch) can produce a `R1CS` (Groth16) or a `SparseR1CS` (PLONK). 

The next few months are very much PLONK / ZK-Rollup focused:
* [v0.4.0](https://github.com/ConsenSys/gnark/milestone/1): coming soon, very experimental without optimizations and PLONK instantiated without KZG polynomial commitment scheme
* [v0.5.0](https://github.com/ConsenSys/gnark/milestone/2): target end of June, PLONK + KZG + efficient instantiation. 
* [v0.6.0](https://github.com/ConsenSys/gnark/milestone/3): not scheduled yet. Likely something close to UltraPLONK.
