### ISSUE TITLE
Example code for emulated elliptic curve group operations fails 

### ISSUE THREAD

**Issue by 311923** [Consensys/gnark#888]
As a first step to learn how emulated arithmetic works, I attempted to run the example code located [here](https://github.com/Consensys/gnark/blob/4dbc3c6be3238987d6cc6daca59d04618470b4ae/std/algebra/emulated/sw_emulated/doc_test.go). 

However, the witness produced by the (unmodified) code does not satisfy the constraints. 

In inspecting the code, I do not understand why the `Res` value in the witness uses `g.X` and `g.Y`; I would have expected `Q.X` and `Q.Y`. (Making these changes does not solve the problem, though.)

Can someone please explain how to get this working? 

Thanks-

**Comment by ivokub** [comment]
There is a typo, in the circuit definition there should be instead:
```go
curve, err := sw_emulated.New[B, S](api, sw_emulated.GetCurveParams[emulated.Secp256k1Fp]()) // NB different type parameter
	if err != nil {
		panic("initalize new curve")
	}
```

Would be great to have a PR!
