### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by chiumichael** [ConsenSys/gnark#96]
Hi there,

I'm trying to build the whole pipeline of circuit compilation, proofing and verification, but I'm encountering a 

`panic: runtime error: index out of range [0] with length 0` 

at the groth16 setup stage. I've tried to closely model this after the example code in the `gnark/examples` directory, so I'm not sure what I'm missing. 

Any help would be greatly appreciated!

```Go

type TestCircuit struct {
	XONE 	frontend.Variable 	`gnark:",public"`
	XTWO 	frontend.Variable 	`gnark:",public"`
}

func (circuit *TestCircuit) Define(curveID ecc.ID, cs *frontend.ConstraintSystem) error {
	my_x2 := cs.Add(circuit.XONE, 0)
	cs.AssertIsEqual(cs.Add(4, my_x2), circuit.XTWO)
	return nil
}

func main() {

	var circuit TestCircuit
	r1cs, err_r1cs := frontend.Compile(ecc.BN254, backend.GROTH16, &circuit)
	if err_r1cs != nil {
		fmt.Println("circuit compilation error")
	}

	var witness TestCircuit
	witness.XONE.Assign(1)
	witness.XTWO.Assign(5)

	_, _, err2 := groth16.Setup(r1cs)	// pk = proving key, vk = verifier key
	if err2 != nil {
		fmt.Println("groth16 setup error")
	}

	// _, err3 := groth16.Prove(r1cs, pk, &witness)
	// if err3 != nil {
	// 	fmt.Println("proof error")
	// }
	// err4 = groth16.Verify(proof, vk, &witness)
	// if err4 != nil {
	// 	fmt.Println("invalid proof")
	// }

}
```

**Comment by ThomasPiellard** [comment]
Hi @chiumichael , so your code is correct, there is a bug on the FFT on our end when the size of the domain is one (it's the case for your circuit because you only have one constraint). The fix will be pushed shortly on gnark-crypto.

Thanks for raising the issue!

**Comment by chiumichael** [comment]
Np, and thanks for the prompt reply! 

I have a quick follow up question though: In the cubic example (`gnark/examples/cubic`), isn't there only one constraint there as well?
