### ISSUE TITLE
How to set bls12_381 G1Affine from [48]frontend.Variable?

### ISSUE THREAD

**Issue by readygo67** [Consensys/gnark#978]
Bls12-381 public key is usually represented by 48 bytes array.  In a my case, a [48]frontend.variable is used to store the publickey bytes,  and I need to rebuild the G1Affine(gnark/std/alegra/emulated/sw_bls12381.go).
Is there any method to achieve this goal?

**Comment by secure12** [comment]
the 48-byte arrays represents points on the curve. Wouldn't it make most sense to convert between the raw bytes with [this](https://github.com/Consensys/gnark-crypto/blob/eb75782795d2d3ce6172797615f8eada77a6a3dd/ecc/bls12-381/marshal.go#L836) and convert to gnark-compatible type with [this](https://github.com/Consensys/gnark/blob/8f954aad54b451cb568ecca64d4d00626a84b49b/std/algebra/emulated/sw_bls12381/g1.go#L22C19-L22C19)?

**Comment by ivokub** [comment]
> the 48-byte arrays represents points on the curve. Wouldn't it make most sense to convert between the raw bytes with [this](https://github.com/Consensys/gnark-crypto/blob/eb75782795d2d3ce6172797615f8eada77a6a3dd/ecc/bls12-381/marshal.go#L836) and convert to gnark-compatible type with [this](https://github.com/Consensys/gnark/blob/8f954aad54b451cb568ecca64d4d00626a84b49b/std/algebra/emulated/sw_bls12381/g1.go#L22C19-L22C19)?

Indeed I would recommend the same approach.
